### ISSUE TITLE
TypefaceManager and Lollipop

### ISSUE THREAD

**Issue by Narayane** [Innovattic/Android-Font-Integration#6]
Hi,

I use your TypefaceManager in my app which is compatible with API 8 and higher.

I have this fonts declaration : 

```xml
<familyset>
    <family>
        <nameset>
            <name>univers_45_light</name>
        </nameset>
        <fileset>
            <file>univers_45_light.ttf</file>
            <file>univers_45_light_bold.ttf</file>
        </fileset>
    </family>
    <family>
        <nameset>
            <name>univers_55_roman</name>
        </nameset>
        <fileset>
            <file>univers_55_roman.ttf</file>
        </fileset>
    </family>
</familyset>
```

Everything works fine on API 19 and below for both but on Lollipop, univers_55_roman is never displayed while univers_45_light is.
However, TypefaceManager seems to do right its job whatever api level is used.

> 03-17 11:53:36.841: I/TypefaceManager(17738): Inflating font univers_55_roman (style 0) with file univers_55_roman.ttf
> 03-17 11:53:45.114: I/TypefaceManager(17738): Inflating font univers_45_light (style 0) with file univers_45_light.ttf
> 03-17 11:53:46.252: I/TypefaceManager(17738): Inflating font univers_45_light (style 1) with file univers_45_light_bold.ttf

Have you ever had this kind of problem on Lollipop ? Maybe is not a TypefaceManager's problem, I am puzzled by the fact one font works and not the other on Lollipop.

Can you help me ?

Thanks.

**Comment by jfresen** [comment]
Hi,
What do you mean by saying the font is never displayed? Do you see the TextView, but it is completely empty despite the fact that you defined a text in there, or is the text displayed correctly, but in the default Android font?
My best guess is there is something about the font file that Android does not understand or like. Try setting the font in a TextView in a bare project using the same build tools and sdk versions as your project. Does it show the font then?
You can set the Typeface manually like this:

```java
public class MainActivity extends Activity {

    private TextView mGnuTypewriter;
    private TextView mXoloniumRegu;
    private TextView mXoloniumBold;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mGnuTypewriter = (TextView) findViewById(R.id.gnu_typewriter);
        mXoloniumRegu = (TextView) findViewById(R.id.xolonium_regular);
        mXoloniumBold = (TextView) findViewById(R.id.xolonium_bold);

        final Typeface fGnuTypewriter = Typeface.createFromAsset(getAssets(), "fonts/gtw.ttf");
        final Typeface fXoloniumRegu = Typeface.createFromAsset(getAssets(), "fonts/Xolonium-Regular.ttf");
        final Typeface fXoloniumBold = Typeface.createFromAsset(getAssets(), "fonts/Xolonium-Bold.ttf");

        mGnuTypewriter.setTypeface(fGnuTypewriter);
        mXoloniumRegu.setTypeface(fXoloniumRegu);
        mXoloniumBold.setTypeface(fXoloniumBold);
    }

}
```

**Comment by Narayane** [comment]
Hi @jfresen ,

What do you mean by saying the font is never displayed? Do you see the TextView, but it is completely empty despite the fact that you defined a text in there, or is the text displayed correctly, but in the default Android font?

Second solution: I see the TextView, my text is visible but in "Droid Sans", not in Universe 55 Roman which is the right font and which is correctly used in API 19 and below but not in API 21.

I will try your suggestion.

**Comment by jfresen** [comment]
If you're able to show the font in the fresh project, your next step would be to set it manually in your app as well, temporarily making the FontTextView a normal TextView. If that shows the font correctly, I think there must indeed be a bug in the TypefaceManager. In that case, I'd like to know on what device you encountered the bug and if it also occurs on an emulator running Lollipop.

**Comment by Narayane** [comment]
Hi @jfresen 

I have same behavior either by using TypefaceManager with a FontTextView or by setting typeface on a regular TextView under Lollipop.

I guess the problem comes from the font Universe 55 itself because Universe 45 works fine on Lollipop

Thanks.

**Comment by jfresen** [comment]
You might try your luck with opening the font with a font editor and saving it again, or converting it to .otf and back to .ttf again. If the error is caused by some glitch in the font file, this might be solved be recreating it.
